framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            cache.blizzard.profile:
                adapter: cache.adapter.redis
                default_lifetime: 1800

            cache.blizzard.gamedata:
                adapter: cache.adapter.redis
                default_lifetime: 604800
